name: kaalan
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+4

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  expand_widget: ^3.1.1
  shimmer: ^3.0.0
  go_router: ^14.2.3
  cached_network_image: ^3.4.1
  http: ^1.2.2
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  rive: ^0.13.4
  sqflite: ^2.3.3+1
  sqflite_common_ffi_web: ^0.4.5+2
  syncfusion_flutter_pdfviewer: ^26.2.9
  flutter_carousel_widget: ^2.3.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.7.10
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3+1
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  introduction_screen: ^3.1.14
  webview_flutter: ^4.8.0
  awesome_dialog: ^3.2.1
  path: ^1.9.0
  fluttertoast: ^8.2.8
  dropdown_button2: ^2.3.9
  circular_bottom_navigation: ^2.4.0
  pin_code_text_field: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/k.png"
  min_sdk_android: 21

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/RiveAssets/
    - shorebird.yaml
  # example:
  fonts:
    - family: Nominee
      fonts:
        - asset: assets/fonts/Nominee-Bold.otf
        - asset: assets/fonts/Nominee-Light.otf
    - family: Intel
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
