// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPTPuRx-yJRcmfyozGToBYYE7S1ic_KE',
    appId: '1:479939089488:web:4b149404f121b1e70f6d55',
    messagingSenderId: '479939089488',
    projectId: 'kaalan-801d7',
    authDomain: 'kaalan-801d7.firebaseapp.com',
    storageBucket: 'kaalan-801d7.appspot.com',
    measurementId: 'G-FVN5909HR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCImL3SmSDHgsiKleGImEICgnVAAn41_as',
    appId: '1:479939089488:android:8de75c68c9539e080f6d55',
    messagingSenderId: '479939089488',
    projectId: 'kaalan-801d7',
    storageBucket: 'kaalan-801d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXOeNHJtuY15jhWOdm7yDCm2F-sUCzIQ',
    appId: '1:479939089488:ios:7d041ae4aeb1b5ce0f6d55',
    messagingSenderId: '479939089488',
    projectId: 'kaalan-801d7',
    storageBucket: 'kaalan-801d7.appspot.com',
    iosBundleId: 'com.example.kaalan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXOeNHJtuY15jhWOdm7yDCm2F-sUCzIQ',
    appId: '1:479939089488:ios:abc7e29cd10641410f6d55',
    messagingSenderId: '479939089488',
    projectId: 'kaalan-801d7',
    storageBucket: 'kaalan-801d7.appspot.com',
    iosBundleId: 'com.example.kaalan.RunnerTests',
  );
}
